# Program to print out two stanzas of Mel the Programmer.
# This wasn't hand-written but autogenerated from a script.
# (c) 2017 Warren Toomey, GPL3
#
	LCB 0
	SMB 0
start:	TBF
	nzvc LCA 0x5 | nzvC LCA 0x7 | nzVc LCA 0x6 | nzVC LCA 0x7 | nZvc LCA 0x7 | nZvC LCA 0x2 | nZVc LCA 0x6 | nZVC LCA 0x4 | Nzvc LCA 0x2 | NzvC LCA 0x6 | NzVc LCA 0x7 | NzVC LCA 0x2 | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x2 | nzvC LCB 0x3 | nzVc LCB 0xe | nzVC LCB 0x3 | nZvc LCB 0x2 | nZvC LCB 0xe | nZVc LCB 0x3 | nZVC LCB 0x4 | Nzvc LCB 0x0 | NzvC LCB 0x3 | NzVc LCB 0x2 | NzVC LCB 0x0 | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x2 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x7 | nZvC LCA 0x0 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x6 | NzvC LCA 0x7 | NzVc LCA 0x6 | NzVC LCA 0x6 | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x5 | nzvC LCB 0x0 | nzVc LCB 0x4 | nzVC LCB 0xf | nZvc LCB 0x5 | nZvC LCB 0xa | nZVc LCB 0x8 | nZVC LCB 0x9 | Nzvc LCB 0x9 | NzvC LCB 0x2 | NzVc LCB 0xf | NzVC LCB 0xe | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x4 | nZVc LCA 0x6 | nZVC LCA 0x7 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC LCA 0x6 | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x1 | nzvC LCB 0x4 | nzVc LCB 0xc | nzVC LCB 0x6 | nZvc LCB 0xd | nZvC LCB 0xe | nZVc LCB 0x9 | nZVC LCB 0x2 | Nzvc LCB 0xe | NzvC LCB 0x9 | NzVc LCB 0x7 | NzVC LCB 0x1 | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x7 | nzVC LCA 0x7 | nZvc LCA 0x7 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x2 | NzvC LCA 0x6 | NzVc LCA 0x7 | NzVC LCA 0x6 | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xc | nzvC LCB 0x5 | nzVc LCB 0x9 | nzVC LCB 0x4 | nZvc LCB 0x3 | nZvC LCB 0xf | nZVc LCB 0xe | nZVC LCB 0x5 | Nzvc LCB 0x0 | NzvC LCB 0x2 | NzVc LCB 0x2 | NzVC LCB 0xd | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x2 | nzvC LCA 0x6 | nzVc LCA 0x2 | nzVC LCA 0x7 | nZvc LCA 0x2 | nZvC LCA 0x7 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC LCA 0x6 | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x0 | nzvC LCB 0x3 | nzVc LCB 0x2 | nzVC LCB 0x7 | nZvc LCB 0x0 | nZvC LCB 0x4 | nZVc LCB 0x5 | nZVC LCB 0x3 | Nzvc LCB 0x9 | NzvC LCB 0x5 | NzVc LCB 0x1 | NzVC LCB 0x5 | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x5 | nzvC LCA 0x6 | nzVc LCA 0x2 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x2 | nZVc LCA 0x2 | nZVC LCA 0x7 | Nzvc LCA 0x6 | NzvC LCA 0x2 | NzVc LCA 0x6 | NzVC LCA 0x2 | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x0 | nzvC LCB 0x1 | nzVc LCB 0x0 | nzVC LCB 0x1 | nZvc LCB 0x1 | nZvC LCB 0x0 | nZVc LCB 0x0 | nZVC LCB 0x4 | Nzvc LCB 0x7 | NzvC LCB 0xc | NzVc LCB 0xd | NzVC LCB 0xe | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x7 | nzvC LCA 0x6 | nzVc LCA 0x7 | nzVC LCA 0x7 | nZvc LCA 0x6 | nZvC LCA 0x4 | nZVc LCA 0x4 | nZVC LCA 0x6 | Nzvc LCA 0x6 | NzvC LCA 0x0 | NzVc LCA 0x6 | NzVC LCA 0x0 | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x2 | nzvC LCB 0x4 | nzVc LCB 0x3 | nzVC LCB 0x2 | nZvc LCB 0xe | nZvC LCB 0x6 | nZVc LCB 0x3 | nZVC LCB 0xc | Nzvc LCB 0xe | NzvC LCB 0xa | NzVc LCB 0xd | NzVC LCB 0xa | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x4 | nZVc LCA 0x6 | nZVC LCA 0x7 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP end | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xf | nzvC LCB 0x5 | nzVc LCB 0xf | nzVC LCB 0x5 | nZvc LCB 0x4 | nZvC LCB 0xf | nZVc LCB 0xf | nZVC LCB 0x9 | Nzvc LCB 0xf | NzvC LCB 0x1 | NzVc LCB 0x5 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x2 | nZvc LCA 0x2 | nZvC LCA 0x5 | nZVc LCA 0x6 | nZVC LCA 0x2 | Nzvc LCA 0x7 | NzvC LCA 0x7 | NzVc LCA 0x7 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x7 | nzvC LCB 0xe | nzVc LCB 0x6 | nzVC LCB 0x2 | nZvc LCB 0x0 | nZvC LCB 0x2 | nZVc LCB 0x4 | nZVC LCB 0xe | Nzvc LCB 0x2 | NzvC LCB 0x3 | NzVc LCB 0x2 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x7 | nzvC LCA 0x7 | nzVc LCA 0x7 | nzVC LCA 0x2 | nZvc LCA 0x7 | nZvC LCA 0x5 | nZVc LCA 0x6 | nZVC LCA 0x0 | Nzvc LCA 0x6 | NzvC LCA 0x2 | NzVc LCA 0x2 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x2 | nzvC LCB 0x4 | nzVc LCB 0x4 | nzVC LCB 0x0 | nZvc LCB 0x6 | nZvC LCB 0x4 | nZVc LCB 0x5 | nZVC LCB 0xa | Nzvc LCB 0x1 | NzvC LCB 0x0 | NzVc LCB 0x0 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x2 | nzVc LCA 0x7 | nzVC LCA 0x7 | nZvc LCA 0x6 | nZvC LCA 0x5 | nZVc LCA 0x2 | nZVC LCA 0x0 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x7 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x1 | nzvC LCB 0x0 | nzVc LCB 0x7 | nzVC LCB 0x3 | nZvc LCB 0x1 | nZvC LCB 0x2 | nZVc LCB 0xe | nZVC LCB 0xa | Nzvc LCB 0xe | NzvC LCB 0x2 | NzVc LCB 0x7 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x4 | nZVc LCA 0x0 | nZVC LCA 0x4 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x7 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xd | nzvC LCB 0x5 | nzVc LCB 0x1 | nzVC LCB 0xf | nZvc LCB 0x3 | nZvC LCB 0x1 | nZVc LCB 0xa | nZVC LCB 0xc | Nzvc LCB 0x3 | NzvC LCB 0x5 | NzVc LCB 0x2 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x7 | nzVc LCA 0x7 | nzVC LCA 0x7 | nZvc LCA 0x7 | nZvC LCA 0x4 | nZVc LCA 0x5 | nZVC LCA 0x6 | Nzvc LCA 0x6 | NzvC LCA 0x7 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xd | nzvC LCB 0x2 | nzVc LCB 0x2 | nzVC LCB 0x5 | nZvc LCB 0x5 | nZvC LCB 0xe | nZVc LCB 0x2 | nZVC LCB 0x5 | Nzvc LCB 0x5 | NzvC LCB 0x3 | NzVc LCB 0xf | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x7 | nZvC LCA 0x2 | nZVc LCA 0x6 | nZVC LCA 0x7 | Nzvc LCA 0x2 | NzvC LCA 0x7 | NzVc LCA 0x7 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x5 | nzvC LCB 0x1 | nzVc LCB 0x5 | nzVC LCB 0xe | nZvc LCB 0x5 | nZvC LCB 0xe | nZVc LCB 0x1 | nZVC LCB 0x3 | Nzvc LCB 0x0 | NzvC LCB 0x4 | NzVc LCB 0x4 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x7 | nzvC LCA 0x2 | nzVc LCA 0x0 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x2 | nZVc LCA 0x7 | nZVC LCA 0x7 | Nzvc LCA 0x6 | NzvC LCA 0x2 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x2 | nzvC LCB 0x0 | nzVc LCB 0xa | nzVC LCB 0x4 | nZvc LCB 0xd | nZvC LCB 0x0 | nZVc LCB 0x7 | nZVC LCB 0x4 | Nzvc LCB 0xf | NzvC LCB 0x0 | NzVc LCB 0x5 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x7 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x2 | nZvC LCA 0x2 | nZVc LCA 0x2 | nZVC LCA 0x2 | Nzvc LCA 0x6 | NzvC LCA 0x4 | NzVc LCA 0x2 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x3 | nzvC LCB 0xf | nzVc LCB 0x2 | nzVC LCB 0x5 | nZvc LCB 0x0 | nZvC LCB 0x0 | nZVc LCB 0xc | nZVC LCB 0x0 | Nzvc LCB 0x6 | NzvC LCB 0x9 | NzVc LCB 0x0 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x2 | nzvC LCA 0x6 | nzVc LCA 0x7 | nzVC LCA 0x6 | nZvc LCA 0x7 | nZvC LCA 0x4 | nZVc LCA 0x2 | nZVC LCA 0x6 | Nzvc LCA 0x2 | NzvC LCA 0x2 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x0 | nzvC LCB 0x6 | nzVc LCB 0x5 | nzVC LCB 0x4 | nZvc LCB 0x4 | nZvC LCB 0xe | nZVc LCB 0x0 | nZVC LCB 0x1 | Nzvc LCB 0x0 | NzvC LCB 0x0 | NzVc LCB 0x3 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x7 | nzvC LCA 0x0 | nzVc LCA 0x7 | nzVC LCA 0x2 | nZvc LCA 0x7 | nZvC LCA 0x6 | nZVc LCA 0x7 | nZVC LCA 0x2 | Nzvc LCA 0x7 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x7 | nzvC LCB 0xa | nzVc LCB 0x4 | nzVC LCB 0x0 | nZvc LCB 0x5 | nZvC LCB 0xf | nZVc LCB 0x5 | nZVC LCB 0x0 | Nzvc LCB 0x4 | NzvC LCB 0x3 | NzVc LCB 0xf | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x7 | nzvC LCA 0x4 | nzVc LCA 0x2 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x7 | nZVc LCA 0x6 | nZVC LCA 0x7 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x2 | nzvC LCB 0xc | nzVc LCB 0x0 | nzVC LCB 0x6 | nZvc LCB 0x2 | nZvC LCB 0x4 | nZVc LCB 0xe | nZVC LCB 0x7 | Nzvc LCB 0x8 | NzvC LCB 0x1 | NzVc LCB 0x4 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x7 | nZvc LCA 0x6 | nZvC LCA 0x2 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x9 | nzvC LCB 0x9 | nzVc LCB 0x2 | nzVC LCB 0x5 | nZvc LCB 0x5 | nZvC LCB 0x0 | nZVc LCB 0x1 | nZVC LCB 0x8 | Nzvc LCB 0x9 | NzvC LCB 0xe | NzVc LCB 0x5 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x7 | nzvC LCA 0x7 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x7 | nZvC LCA 0x5 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x7 | NzvC LCA 0x2 | NzVc LCA 0x2 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x4 | nzvC LCB 0x4 | nzVc LCB 0x1 | nzVC LCB 0xe | nZvc LCB 0x3 | nZvC LCB 0x2 | nZVc LCB 0x4 | nZVC LCB 0xf | Nzvc LCB 0x3 | NzvC LCB 0x0 | NzVc LCB 0xe | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x2 | nZvC LCA 0x4 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x2 | NzvC LCA 0x7 | NzVc LCA 0x0 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x5 | nzvC LCB 0x5 | nzVc LCB 0x3 | nzVC LCB 0xe | nZvc LCB 0xc | nZvC LCB 0x1 | nZVc LCB 0xf | nZVC LCB 0xc | Nzvc LCB 0x0 | NzvC LCB 0x4 | NzVc LCB 0xa | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x2 | nzvC LCA 0x2 | nzVc LCA 0x6 | nzVC LCA 0x7 | nZvc LCA 0x0 | nZvC LCA 0x5 | nZVc LCA 0x7 | nZVC LCA 0x6 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x4 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x0 | nzvC LCB 0x0 | nzVc LCB 0xb | nzVC LCB 0x9 | nZvc LCB 0xa | nZvC LCB 0x4 | nZVc LCB 0x2 | nZVC LCB 0x5 | Nzvc LCB 0x7 | NzvC LCB 0x8 | NzVc LCB 0x9 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x2 | nzVC LCA 0x0 | nZvc LCA 0x5 | nZvC LCA 0x4 | nZVc LCA 0x6 | nZVC LCA 0x2 | Nzvc LCA 0x6 | NzvC LCA 0x7 | NzVc LCA 0x2 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x9 | nzvC LCB 0x2 | nzVc LCB 0x0 | nzVC LCB 0xa | nZvc LCB 0x2 | nZvC LCB 0x6 | nZVc LCB 0xe | nZVC LCB 0x0 | Nzvc LCB 0xc | NzvC LCB 0x2 | NzVc LCB 0x7 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x4 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xe | nzvC LCB 0x5 | nzVc LCB 0x9 | nzVC LCB 0x1 | nZvc LCB 0x5 | nZvC LCB 0xf | nZVc LCB 0x5 | nZVC LCB 0xe | Nzvc LCB 0xf | NzvC LCB 0xf | NzVc LCB 0xc | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x2 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x5 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x7 | NzvC LCA 0x7 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x0 | nzvC LCB 0x5 | nzVc LCB 0xe | nzVC LCB 0xe | nZvc LCB 0x1 | nZvC LCB 0x2 | nZVc LCB 0x4 | nZVC LCB 0x5 | Nzvc LCB 0x2 | NzvC LCB 0x5 | NzVc LCB 0xc | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x4 | nzvC LCA 0x7 | nzVc LCA 0x2 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x2 | nZVc LCA 0x2 | nZVC LCA 0x7 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x2 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x6 | nzvC LCB 0x2 | nzVc LCB 0x0 | nzVC LCB 0x4 | nZvc LCB 0xc | nZvC LCB 0xe | nZVc LCB 0xc | nZVC LCB 0x7 | Nzvc LCB 0x9 | NzvC LCB 0x7 | NzVc LCB 0x0 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x4 | nzvC LCA 0x2 | nzVc LCA 0x7 | nzVC LCA 0x2 | nZvc LCA 0x2 | nZvC LCA 0x2 | nZVc LCA 0x2 | nZVC LCA 0x2 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xf | nzvC LCB 0xc | nzVc LCB 0x4 | nzVC LCB 0x0 | nZvc LCB 0x0 | nZvC LCB 0x0 | nZVc LCB 0x0 | nZVC LCB 0x0 | Nzvc LCB 0xf | NzvC LCB 0x8 | NzVc LCB 0x3 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x5 | nzvC LCA 0x2 | nzVc LCA 0x6 | nzVC LCA 0x5 | nZvc LCA 0x5 | nZvC LCA 0x2 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x7 | NzvC LCA 0x2 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x2 | nzvC LCB 0x0 | nzVc LCB 0x8 | nzVC LCB 0x2 | nZvc LCB 0x0 | nZvC LCB 0x0 | nZVc LCB 0x9 | nZVC LCB 0x7 | Nzvc LCB 0x5 | NzvC LCB 0x0 | NzVc LCB 0x1 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x5 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x7 | nZvC LCA 0x4 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x7 | NzvC LCA 0x7 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x4 | nzvC LCB 0x8 | nzVc LCB 0x5 | nzVC LCB 0x5 | nZvc LCB 0x2 | nZvC LCB 0xe | nZVc LCB 0xe | nZVC LCB 0x5 | Nzvc LCB 0x3 | NzvC LCB 0x4 | NzVc LCB 0xc | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x5 | nzvC LCA 0x6 | nzVc LCA 0x2 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x6 | nZVc LCA 0x7 | nZVC LCA 0x6 | Nzvc LCA 0x2 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x2 | nzvC LCB 0x1 | nzVc LCB 0x0 | nzVC LCB 0x1 | nZvc LCB 0xf | nZvC LCB 0xf | nZVc LCB 0x3 | nZVC LCB 0xe | Nzvc LCB 0x0 | NzvC LCB 0x8 | NzVc LCB 0xc | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x4 | nzvC LCA 0x6 | nzVc LCA 0x4 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x7 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x7 | NzvC LCA 0x6 | NzVc LCA 0x2 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x1 | nzvC LCB 0xe | nzVc LCB 0x7 | nzVC LCB 0xc | nZvc LCB 0x7 | nZvC LCB 0x4 | nZVc LCB 0x3 | nZVC LCB 0x5 | Nzvc LCB 0x0 | NzvC LCB 0x5 | NzVc LCB 0x0 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x4 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x2 | nZvc LCA 0x7 | nZvC LCA 0x2 | nZVc LCA 0x7 | nZVC LCA 0x7 | Nzvc LCA 0x6 | NzvC LCA 0x2 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xe | nzvC LCB 0x4 | nzVc LCB 0xf | nzVC LCB 0x0 | nZvc LCB 0x2 | nZvC LCB 0xc | nZVc LCB 0x2 | nZVC LCB 0x2 | Nzvc LCB 0x1 | NzvC LCB 0x0 | NzVc LCB 0x8 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x2 | nzvC LCA 0x2 | nzVc LCA 0x6 | nzVC LCA 0x4 | nZvc LCA 0x6 | nZvC LCA 0x2 | nZVc LCA 0x7 | nZVC LCA 0x6 | Nzvc LCA 0x7 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xe | nzvC LCB 0x0 | nzVc LCB 0xf | nzVC LCB 0x3 | nZvc LCB 0x1 | nZvC LCB 0x0 | nZVc LCB 0x5 | nZVC LCB 0x1 | Nzvc LCB 0x3 | NzvC LCB 0x7 | NzVc LCB 0x9 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x0 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x6 | nZVc LCA 0x7 | nZVC LCA 0x7 | Nzvc LCA 0x7 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xa | nzvC LCB 0x3 | nzVc LCB 0x4 | nzVC LCB 0xf | nZvc LCB 0xd | nZvC LCB 0x5 | nZVc LCB 0x4 | nZVC LCB 0x4 | Nzvc LCB 0x4 | NzvC LCB 0x5 | NzVc LCB 0xd | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x0 | nzvC LCA 0x6 | nzVc LCA 0x2 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x7 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x2 | NzvC LCA 0x6 | NzVc LCA 0x2 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xa | nzvC LCB 0x1 | nzVc LCB 0x0 | nzVC LCB 0xd | nZvc LCB 0xd | nZvC LCB 0x6 | nZVc LCB 0x1 | nZVC LCB 0x9 | Nzvc LCB 0xc | NzvC LCB 0xe | NzVc LCB 0x0 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x4 | nzvC LCA 0x6 | nzVc LCA 0x4 | nzVC LCA 0x7 | nZvc LCA 0x6 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x0 | NzvC LCA 0x6 | NzVc LCA 0x4 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xd | nzvC LCB 0xc | nzVc LCB 0xf | nzVC LCB 0x0 | nZvc LCB 0x5 | nZvC LCB 0x5 | nZVc LCB 0x2 | nZVC LCB 0xf | Nzvc LCB 0xa | NzvC LCB 0x5 | NzVc LCB 0xd | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x7 | nZvc LCA 0x7 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x4 | NzvC LCA 0x7 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x1 | nzvC LCB 0x3 | nzVc LCB 0xc | nzVC LCB 0x5 | nZvc LCB 0x2 | nZvC LCB 0xe | nZVc LCB 0xc | nZVC LCB 0xe | Nzvc LCB 0x9 | NzvC LCB 0x2 | NzVc LCB 0x5 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x7 | nzvC LCA 0x7 | nzVc LCA 0x6 | nzVC LCA 0x7 | nZvc LCA 0x7 | nZvC LCA 0x2 | nZVc LCA 0x6 | nZVC LCA 0x2 | Nzvc LCA 0x2 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x9 | nzvC LCB 0x5 | nzVc LCB 0x4 | nzVC LCB 0x4 | nZvc LCB 0x3 | nZvC LCB 0xc | nZVc LCB 0x5 | nZVC LCB 0x0 | Nzvc LCB 0x0 | NzvC LCB 0x1 | NzVc LCB 0xc | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x2 | nzVC LCA 0x6 | nZvc LCA 0x2 | nZvC LCA 0x2 | nZVc LCA 0x2 | nZVC LCA 0x6 | Nzvc LCA 0x6 | NzvC LCA 0x7 | NzVc LCA 0x2 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x2 | nzvC LCB 0xc | nzVc LCB 0x0 | nzVC LCB 0x5 | nZvc LCB 0x0 | nZvC LCB 0x0 | nZVc LCB 0x0 | nZVC LCB 0xf | Nzvc LCB 0x6 | NzvC LCB 0x4 | NzVc LCB 0xc | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x4 | nzVC LCA 0x7 | nZvc LCA 0x7 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x0 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x5 | nzvC LCB 0x1 | nzVc LCB 0x4 | nzVC LCB 0x2 | nZvc LCB 0x7 | nZvC LCB 0x1 | nZVc LCB 0x8 | nZVC LCB 0x6 | Nzvc LCB 0x5 | NzvC LCB 0x9 | NzVc LCB 0xa | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x2 | nzvC LCA 0x7 | nzVc LCA 0x6 | nzVC LCA 0x7 | nZvc LCA 0x7 | nZvC LCA 0x7 | nZVc LCA 0x6 | nZVC LCA 0x2 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x0 | nzvC LCB 0x4 | nzVc LCB 0x1 | nzVC LCB 0x3 | nZvc LCB 0x2 | nZvC LCB 0x3 | nZVc LCB 0x5 | nZVC LCB 0x0 | Nzvc LCB 0x5 | NzvC LCB 0xf | NzVc LCB 0x2 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x7 | nzvC LCA 0x6 | nzVc LCA 0x7 | nzVC LCA 0x2 | nZvc LCA 0x6 | nZvC LCA 0x7 | nZVc LCA 0x7 | nZVC LCA 0x7 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x4 | nzvC LCB 0xf | nzVc LCB 0x9 | nzVC LCB 0x0 | nZvc LCB 0xf | nZvC LCB 0x3 | nZVc LCB 0x8 | nZVC LCB 0x0 | Nzvc LCB 0xc | NzvC LCB 0xe | NzVc LCB 0x5 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x7 | nzVc LCA 0x7 | nzVC LCA 0x7 | nZvc LCA 0x7 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x7 | Nzvc LCA 0x2 | NzvC LCA 0x2 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x8 | nzvC LCB 0x2 | nzVc LCB 0x3 | nzVC LCB 0x7 | nZvc LCB 0x4 | nZvC LCB 0x5 | nZVc LCB 0x1 | nZVC LCB 0x2 | Nzvc LCB 0x0 | NzvC LCB 0x0 | NzVc LCB 0x3 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x7 | nzVc LCA 0x2 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x5 | nzvC LCB 0x3 | nzVc LCB 0xc | nzVC LCB 0x5 | nZvc LCB 0x5 | nZvC LCB 0xd | nZVc LCB 0x4 | nZVC LCB 0xf | Nzvc LCB 0x4 | NzvC LCB 0x7 | NzVc LCB 0x1 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x7 | nzvC LCA 0x2 | nzVc LCA 0x0 | nzVC LCA 0x7 | nZvc LCA 0x2 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x7 | NzvC LCA 0x6 | NzVc LCA 0x7 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x9 | nzvC LCB 0xc | nzVc LCB 0xa | nzVC LCB 0x2 | nZvc LCB 0x0 | nZvC LCB 0x2 | nZVc LCB 0x5 | nZVC LCB 0x7 | Nzvc LCB 0x5 | NzvC LCB 0x1 | NzVc LCB 0x5 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x2 | nzvC LCA 0x2 | nzVc LCA 0x7 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x7 | Nzvc LCA 0x7 | NzvC LCA 0x7 | NzVc LCA 0x7 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x0 | nzvC LCB 0x0 | nzVc LCB 0x7 | nzVC LCB 0x5 | nZvc LCB 0x9 | nZvC LCB 0xc | nZVc LCB 0x3 | nZVC LCB 0x2 | Nzvc LCB 0x4 | NzvC LCB 0x0 | NzVc LCB 0x3 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x2 | nZvc LCA 0x6 | nZvC LCA 0x7 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x7 | NzvC LCA 0x2 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x4 | nzvC LCB 0x1 | nzVc LCB 0x8 | nzVC LCB 0x0 | nZvc LCB 0xe | nZvC LCB 0x9 | nZVc LCB 0x9 | nZVC LCB 0x1 | Nzvc LCB 0x9 | NzvC LCB 0xc | NzVc LCB 0x5 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x2 | nZvC LCA 0x2 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x2 | NzvC LCA 0x0 | NzVc LCA 0x2 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xf | nzvC LCB 0xe | nzVc LCB 0x5 | nzVC LCB 0xd | nZvc LCB 0x0 | nZvC LCB 0x0 | nZVc LCB 0xd | nZVC LCB 0xd | Nzvc LCB 0xd | NzvC LCB 0xa | NzVc LCB 0x0 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x2 | nzvC LCA 0x6 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x7 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x0 | nzvC LCB 0x4 | nzVc LCB 0xe | nzVC LCB 0x1 | nZvc LCB 0xd | nZvC LCB 0xc | nZVc LCB 0x1 | nZVC LCB 0xd | Nzvc LCB 0x2 | NzvC LCB 0x8 | NzVc LCB 0x4 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x2 | nzVc LCA 0x2 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xe | nzvC LCB 0x0 | nzVc LCB 0x0 | nzVC LCB 0x4 | nZvc LCB 0x1 | nZvC LCB 0x1 | nZVc LCB 0xc | nZVC LCB 0x5 | Nzvc LCB 0xf | NzvC LCB 0xf | NzVc LCB 0x8 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x2 | nzVc LCA 0x7 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x6 | nZVc LCA 0x2 | nZVC LCA 0x7 | Nzvc LCA 0x7 | NzvC LCA 0x7 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xf | nzvC LCB 0x2 | nzVc LCB 0x4 | nzVC LCB 0x5 | nZvc LCB 0x3 | nZvC LCB 0xe | nZVc LCB 0x0 | nZVC LCB 0x2 | Nzvc LCB 0x5 | NzvC LCB 0x7 | NzVc LCB 0x1 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x7 | nzvC LCA 0x7 | nzVc LCA 0x6 | nzVC LCA 0x2 | nZvc LCA 0x6 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x7 | Nzvc LCA 0x6 | NzvC LCA 0x2 | NzVc LCA 0x7 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x7 | nzvC LCB 0x5 | nzVc LCB 0x8 | nzVC LCB 0x0 | nZvc LCB 0x8 | nZvC LCB 0x7 | nZVc LCB 0xe | nZVC LCB 0x3 | Nzvc LCB 0xe | NzvC LCB 0x0 | NzVc LCB 0x4 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x2 | nzvC LCA 0x7 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x7 | nZVc LCA 0x7 | nZVC LCA 0x0 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x2 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xc | nzvC LCB 0x3 | nzVc LCB 0x5 | nzVC LCB 0xf | nZvc LCB 0x9 | nZvC LCB 0x5 | nZVc LCB 0x5 | nZVC LCB 0xa | Nzvc LCB 0x4 | NzvC LCB 0x1 | NzVc LCB 0x0 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x0 | nzvC LCA 0x6 | nzVc LCA 0x2 | nzVC LCA 0x7 | nZvc LCA 0x6 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x2 | NzvC LCA 0x2 | NzVc LCA 0x7 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xa | nzvC LCB 0x5 | nzVc LCB 0x0 | nzVC LCB 0x5 | nZvc LCB 0xe | nZvC LCB 0x1 | nZVc LCB 0xd | nZVC LCB 0x7 | Nzvc LCB 0x0 | NzvC LCB 0x0 | NzVc LCB 0x7 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x7 | nzVc LCA 0x7 | nzVC LCA 0x7 | nZvc LCA 0x6 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x7 | Nzvc LCA 0x7 | NzvC LCA 0x5 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x9 | nzvC LCB 0x2 | nzVc LCB 0x4 | nzVC LCB 0x4 | nZvc LCB 0x5 | nZvC LCB 0x7 | nZVc LCB 0x2 | nZVC LCB 0x2 | Nzvc LCB 0x4 | NzvC LCB 0x2 | NzVc LCB 0x1 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x2 | nzVc LCA 0x6 | nzVC LCA 0x2 | nZvc LCA 0x2 | nZvC LCA 0x6 | nZVc LCA 0x6 | nZVC LCA 0x6 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x7 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0xe | nzvC LCB 0xd | nzVc LCB 0x5 | nzVC LCB 0x0 | nZvc LCB 0x0 | nZvC LCB 0x5 | nZVc LCB 0x5 | nZVC LCB 0xf | Nzvc LCB 0xf | NzvC LCB 0x5 | NzVc LCB 0x3 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x2 | nzvC LCA 0x6 | nzVc LCA 0x7 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x2 | nZVc LCA 0x7 | nZVC LCA 0x7 | Nzvc LCA 0x2 | NzvC LCA 0x6 | NzVc LCA 0x2 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x0 | nzvC LCB 0x6 | nzVc LCB 0x2 | nzVC LCB 0xf | nZvc LCB 0x3 | nZvC LCB 0xe | nZVc LCB 0x2 | nZVC LCB 0x7 | Nzvc LCB 0x0 | NzvC LCB 0x1 | NzVc LCB 0x0 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x7 | nzvC LCA 0x7 | nzVc LCA 0x6 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x0 | nZVc LCA 0x7 | nZVC LCA 0x2 | Nzvc LCA 0x6 | NzvC LCA 0x6 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x4 | nzvC LCB 0x2 | nzVc LCB 0xd | nzVC LCB 0x6 | nZvc LCB 0xf | nZvC LCB 0xa | nZVc LCB 0x3 | nZVC LCB 0x0 | Nzvc LCB 0x4 | NzvC LCB 0xc | NzVc LCB 0x8 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x2 | nzVC LCA 0x2 | nZvc LCA 0x6 | nZvC LCA 0x4 | nZVc LCA 0x2 | nZVC LCA 0x7 | Nzvc LCA 0x6 | NzvC LCA 0x2 | NzVc LCA 0x6 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x8 | nzvC LCB 0x9 | nzVc LCB 0x0 | nzVC LCB 0x0 | nZvc LCB 0x4 | nZvC LCB 0xd | nZVc LCB 0xe | nZVC LCB 0x5 | Nzvc LCB 0x5 | NzvC LCB 0x0 | NzVc LCB 0x9 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
	nzvc LCA 0x6 | nzvC LCA 0x6 | nzVc LCA 0x2 | nzVC LCA 0x6 | nZvc LCA 0x6 | nZvC LCA 0x6 | nZVc LCA 0x0 | nZVC LCA 0x7 | Nzvc LCA 0x7 | NzvC LCA 0x5 | NzVc LCA 0x7 | NzVC JMP inc | NZvc JMP inc | NZvC JMP inc | NZVc JMP inc | NZVC JMP inc
	nzvc LCB 0x9 | nzvC LCB 0x5 | nzVc LCB 0x2 | nzVC LCB 0x4 | nZvc LCB 0x5 | nZvC LCB 0x1 | nZVc LCB 0xa | nZVC LCB 0x0 | Nzvc LCB 0x3 | NzvC LCB 0x0 | NzVc LCB 0x3 | NzVC NOP | NZvc NOP | NZvC NOP | NZVc NOP | NZVC NOP
	DMAB 0
	TBF
inc:	LMA 0
	LCB 1
	CLC
	ADDMB 0
	JMP start
end:	JMP end
